### ISSUE TITLE
microk8s.daemon-kubelet fails on boot

### ISSUE THREAD

**Issue by moonmeister** [ubuntu/microk8s#423]
On boot the `microk8s.daemon-kubelet` fails to start. currently running `microk8s.stop && microk8s.start` fixes the problem...it's just annoying. Thanks for the help!

![k8s](https://user-images.githubusercontent.com/2730871/55850024-536de600-5b85-11e9-8f02-3051b0a12fdc.PNG)

```sh
Started Kubernetes systemd probe.
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: I0403 09:39:56.924370    2250 server.go:417] Version: v1.14.0
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: I0403 09:39:56.924495    2250 plugins.go:103] No cloud provider specified.
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: I0403 09:39:56.927772    2250 server.go:625] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: I0403 09:39:56.927949    2250 container_manager_linux.go:261] container manager verified user specified cgroup-root exists: []
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: I0403 09:39:56.927961    2250 container_manager_linux.go:266] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:remote CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:cgroupfs K
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: I0403 09:39:56.928008    2250 container_manager_linux.go:286] Creating device plugin manager: true
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: I0403 09:39:56.928026    2250 state_mem.go:36] [cpumanager] initializing new in-memory state store
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: I0403 09:39:56.928077    2250 state_mem.go:84] [cpumanager] updated default cpuset: ""
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: I0403 09:39:56.928083    2250 state_mem.go:92] [cpumanager] updated cpuset assignments: "map[]"
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: I0403 09:39:56.928139    2250 kubelet.go:304] Watching apiserver
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: E0403 09:39:56.928432    2250 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get http://127.0.0.1:8080/api/v1/pods?fieldSelector=spec.nodeName%3Dcor-sv-ci01&limit=500&resourceVersion=0: dial tcp 127.0.0.1:808
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: E0403 09:39:56.928504    2250 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/kubelet.go:442: Failed to list *v1.Service: Get http://127.0.0.1:8080/api/v1/services?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8080: connect: connection refused
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: E0403 09:39:56.928681    2250 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/kubelet.go:451: Failed to list *v1.Node: Get http://127.0.0.1:8080/api/v1/nodes?fieldSelector=metadata.name%3Dcor-sv-ci01&limit=500&resourceVersion=0: dial tcp 127.0.0.1:8080: con
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: W0403 09:39:56.929259    2250 util_unix.go:77] Using "/var/snap/microk8s/common/run/containerd.sock" as endpoint is deprecated, please consider using full url format "unix:///var/snap/microk8s/common/run/containerd.sock".
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: I0403 09:39:56.929287    2250 remote_runtime.go:62] parsed scheme: ""
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: I0403 09:39:56.929294    2250 remote_runtime.go:62] scheme "" not registered, fallback to default scheme
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: W0403 09:39:56.929307    2250 util_unix.go:77] Using "/var/snap/microk8s/common/run/containerd.sock" as endpoint is deprecated, please consider using full url format "unix:///var/snap/microk8s/common/run/containerd.sock".
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: I0403 09:39:56.929315    2250 remote_image.go:50] parsed scheme: ""
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: I0403 09:39:56.929319    2250 remote_image.go:50] scheme "" not registered, fallback to default scheme
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: I0403 09:39:56.929396    2250 asm_amd64.s:1337] ccResolverWrapper: sending new addresses to cc: [{/var/snap/microk8s/common/run/containerd.sock 0  <nil>}]
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: I0403 09:39:56.929404    2250 asm_amd64.s:1337] ccResolverWrapper: sending new addresses to cc: [{/var/snap/microk8s/common/run/containerd.sock 0  <nil>}]
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: I0403 09:39:56.929408    2250 clientconn.go:796] ClientConn switching balancer to "pick_first"
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: I0403 09:39:56.929411    2250 clientconn.go:796] ClientConn switching balancer to "pick_first"
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: I0403 09:39:56.929432    2250 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc000279b40, CONNECTING
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: I0403 09:39:56.929435    2250 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc0002ae200, CONNECTING
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: I0403 09:39:56.929503    2250 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc000279b40, READY
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: I0403 09:39:56.929521    2250 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc0002ae200, READY
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: E0403 09:39:56.929934    2250 remote_runtime.go:85] Version from runtime service failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: E0403 09:39:56.929976    2250 kuberuntime_manager.go:196] Get runtime version failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService
Apr 03 09:39:56 cor-sv-ci01 microk8s.daemon-kubelet[2250]: F0403 09:39:56.929987    2250 server.go:265] failed to run Kubelet: failed to create kubelet: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService
Apr 03 09:39:56 cor-sv-ci01 systemd[1]: snap.microk8s.daemon-kubelet.service: Main process exited, code=exited, status=255/n/a
Apr 03 09:39:56 cor-sv-ci01 systemd[1]: snap.microk8s.daemon-kubelet.service: Failed with result 'exit-code'.
Apr 03 09:39:57 cor-sv-ci01 microk8s.daemon-scheduler[1454]: E0403 09:39:57.121024    1454 reflector.go:126] k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:223: Failed to list *v1.Pod: Get http://127.0.0.1:8080/api/v1/pods?fieldSelector=status.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&limit=500&resourceVe
Apr 03 09:39:57 cor-sv-ci01 microk8s.daemon-scheduler[1454]: E0403 09:39:57.121940    1454 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Node: Get http://127.0.0.1:8080/api/v1/nodes?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8080: connect: connection refused
Apr 03 09:39:57 cor-sv-ci01 microk8s.daemon-scheduler[1454]: E0403 09:39:57.122831    1454 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.ReplicaSet: Get http://127.0.0.1:8080/apis/apps/v1/replicasets?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8080: connect: connection refused
Apr 03 09:39:57 cor-sv-ci01 microk8s.daemon-scheduler[1454]: E0403 09:39:57.123915    1454 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.PersistentVolume: Get http://127.0.0.1:8080/api/v1/persistentvolumes?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8080: connect: connection re
Apr 03 09:39:57 cor-sv-ci01 microk8s.daemon-scheduler[1454]: E0403 09:39:57.124987    1454 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.PodDisruptionBudget: Get http://127.0.0.1:8080/apis/policy/v1beta1/poddisruptionbudgets?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8080
Apr 03 09:39:57 cor-sv-ci01 microk8s.daemon-scheduler[1454]: E0403 09:39:57.126115    1454 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.PersistentVolumeClaim: Get http://127.0.0.1:8080/api/v1/persistentvolumeclaims?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8080: connect: con
Apr 03 09:39:57 cor-sv-ci01 microk8s.daemon-scheduler[1454]: E0403 09:39:57.127027    1454 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.StorageClass: Get http://127.0.0.1:8080/apis/storage.k8s.io/v1/storageclasses?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8080: connect: conn
Apr 03 09:39:57 cor-sv-ci01 microk8s.daemon-scheduler[1454]: E0403 09:39:57.128086    1454 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.ReplicationController: Get http://127.0.0.1:8080/api/v1/replicationcontrollers?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8080: connect: con
Apr 03 09:39:57 cor-sv-ci01 microk8s.daemon-scheduler[1454]: E0403 09:39:57.129175    1454 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.StatefulSet: Get http://127.0.0.1:8080/apis/apps/v1/statefulsets?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8080: connect: connection refuse
Apr 03 09:39:57 cor-sv-ci01 microk8s.daemon-scheduler[1454]: E0403 09:39:57.130437    1454 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Service: Get http://127.0.0.1:8080/api/v1/services?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8080: connect: connection refused
Apr 03 09:39:57 cor-sv-ci01 microk8s.daemon-apiserver[1245]: Waiting for default route to appear. (attempt 1)
Apr 03 09:39:57 cor-sv-ci01 microk8s.daemon-proxy[1475]: Waiting for default route to appear. (attempt 1)
Apr 03 09:39:57 cor-sv-ci01 systemd[1]: snap.microk8s.daemon-kubelet.service: Service hold-off time over, scheduling restart.
lines 49452-49514
```

[inspection-report-20190410_034125.tar.gz](https://github.com/ubuntu/microk8s/files/3061879/inspection-report-20190410_034125.tar.gz)

**Comment by moonmeister** [comment]
Looks like this might be related: https://github.com/containerd/cri/issues/619

**Comment by moonmeister** [comment]
Updating to candidate release didn't help. I did add a cron job to fix this for now. `sleep 30 && microk8s.stop && microk8s.start`.

**Comment by ktsakalozos** [comment]
@moonmeister thank you for reporting this. I think I see what happens. If you look at the `snap.microk8s.daemon-kubelet/journal.log`  at `Apr 09 20:50:26` you will see kubelet trying to start after a reboot. Kubelet tries to boot and fails with:
```
Apr 09 20:50:33 cor-sv-ci01 microk8s.daemon-kubelet[2418]: E0409 20:50:33.925083    2418 remote_runtime.go:85] Version from runtime service failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService
Apr 09 20:50:33 cor-sv-ci01 microk8s.daemon-kubelet[2418]: E0409 20:50:33.925143    2418 kuberuntime_manager.go:196] Get runtime version failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService
Apr 09 20:50:33 cor-sv-ci01 microk8s.daemon-kubelet[2418]: F0409 20:50:33.925153    2418 server.go:265] failed to run Kubelet: failed to create kubelet: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService
```
Kubelet tries to boot again and it fails too quickly so snapd stops retrying to boot kubelet:
```
Apr 09 20:50:34 cor-sv-ci01 systemd[1]: snap.microk8s.daemon-kubelet.service: Service hold-off time over, scheduling restart.
Apr 09 20:50:34 cor-sv-ci01 systemd[1]: snap.microk8s.daemon-kubelet.service: Scheduled restart job, restart counter is at 5.
Apr 09 20:50:34 cor-sv-ci01 systemd[1]: Stopped Service for snap application microk8s.daemon-kubelet.
Apr 09 20:50:34 cor-sv-ci01 systemd[1]: snap.microk8s.daemon-kubelet.service: Start request repeated too quickly.
Apr 09 20:50:34 cor-sv-ci01 systemd[1]: snap.microk8s.daemon-kubelet.service: Failed with result 'exit-code'.
Apr 09 20:50:34 cor-sv-ci01 systemd[1]: Failed to start Service for snap application microk8s.daemon-kubelet.
```

At the same time in `snap.microk8s.daemon-containerd/journal.log` we have this warning. 
```
Apr 09 20:50:29 cor-sv-ci01 microk8s.daemon-containerd[1422]: time="2019-04-09T20:50:29.135297561Z" level=warning msg="failed to load plugin io.containerd.grpc.v1.cri" error="failed to create CRI service: failed to create stream server: failed to get stream server address: no default routes found in "/proc/net/route" or "/proc/net/ipv6_route""
```
Containerd complains that there is no default route.

We are waiting for a default route to be present in the case of kube-apiserver and kube-proxy services:
https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/run-with-config-args#L30
We do not wait for a default route to start containerd: https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/run-containerd-with-args
I suspect we need the same "wait for default route" logic there.

**Comment by moonmeister** [comment]
@ktsakalozos Thanks for the reply! I missed the containerd log. This explains why I had to wait a little to run the stop/start cause if I didn't network still wasn't up. I'll  log an issue on my side to remove my fix once a fix is released.

**Comment by ktsakalozos** [comment]
@moonmeister I am finding it difficult to reproduce the issue you are seeing and therefore validate the fix. Would it be possible for you to give it a try?
```
sudo snap install microk8s --classic --channel edge/reboot-fix
```

Many thanks

**Comment by moonmeister** [comment]
Hey, sry. Thought I responded via email but it looks like it never arrived. I'll test this tomorrow.

**Comment by moonmeister** [comment]
@ktsakalozos Hey, this was for a client of the company I work for...circumstances have changed and I'm no longer able to test this. Sorry. I know this was running on Ubuntu 18.04 installed on a bare-metal Dell R240 server. Not sure if it was DHCP or Static I didn't do the HW setup.

**Comment by alawami** [comment]
I am having the same problem, except `micok8s.stop & microk8s.start` does not solve the problem. Similarly the fix (`sudo snap install microk8s --classic --channel edge/reboot-fix`) did not resolve the problem.

**Comment by ktsakalozos** [comment]
@alawami could you share the tarball produced by `microk8s.inspect` and (if possible) a way for me to reproduce the error you are seeing on a clean machine (eg on a public cloud)? Thank you

**Comment by nitikornchumnankul** [comment]
@ktsakalozos I use `` sudo systemctl restart snap.microk8s.daemon-kubelet`` .  it's working for me.
